### ISSUE TITLE
non-DA engineering test problem on Hera

### ISSUE THREAD

**Issue by MatthewPyle-NOAA** [NOAA-EMC/rrfs-workflow#101]
While testing a recent PR on Hera, I had a forecast job failure.  There was an inconsistency in the resources specified for the forecast job. The parameter files specified a 2 x 5 + 20 quilt (so 30 tasks total), but the .xml was providing 36 tasks (3x12). Changing the .xml to be 30 tasks (3x10) got it running.  Also wondering why so many quilt server tasks are being used.  Just making a note of this item on a Friday afternoon - haven't dug any further into it.

**Comment by chan-hoo** [comment]
I'll take a look at this.

**Comment by chan-hoo** [comment]
WRTCMP_write_tasks_per_group=20 is its default value. I'll put ` WRTCMP_write_tasks_per_group=$(( 1*LAYOUT_Y ))` into RRFS_CONUS_25km
