### ISSUE TITLE
Need to add cmake flags not to compile unnecessary executables for RRFS in UFS_UTILS

### ISSUE THREAD

**Issue by chan-hoo** [NOAA-EMC/rrfs-workflow#106]
- Currently, all executables in UFS_UTILS are compiled in the build step. However, NCO requires that the specific executables necessary for RRFS should be compiled.

**Comment by MatthewPyle-NOAA** [comment]
@chan-hoo Is it more about building unneeded components, or copying them to the exec/ directory?  I'm just thinking back to WRF model days, where a build would create 5+ executables but we really just needed two of them.  I think the ideal would be to avoid building what isn't needed, but when that isn't possible, avoiding copying them to the final directory would be the next best thing.

**Comment by chan-hoo** [comment]
@MatthewPyle-NOAA, the first thing (building) is what NCO wants. Currently, the version of UFS_UTILS used for AQM.v7 has this option to build only the selected components. I think this is the release version and it is not the same as what RRFS uses now. I agree with you. We can use the second thing (copying) until this option is available in the develop branch of UFS_UTILS (rrfs_utl as well).
