### ISSUE TITLE
J-job names do not match with ex-script names in some tasks

### ISSUE THREAD

**Issue by chan-hoo** [NOAA-EMC/rrfs-workflow#109]
In some tasks, the file name of the J-job is different from that of the ex-script.
For example,
- JRRFS_RUN_ANAL  <-> exrrfs_run_analysis.sh
- JRRFS_NONVARCLD <-> exrrfs_nonvarcldanl.sh
- JRRFS_RUN_ENSPOST <-> exrrfs_enspost.py 
- JRRFS_PROCESS_GLMFED <-> exrrfs_prep_glmfed.py

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA  These 3 ex-scripts don't seem to be associated with a J-job and I can't find where they are called:
exrrfs_archive_emc.ksh
exrrfs_archive_ens.ksh
exrrfs_clean.ksh

Do you know if they are used/needed?

**Comment by BenjaminBlake-NOAA** [comment]
This issue was resolved with PR #243
