### ISSUE TITLE
Some modules are loaded twice on WCOSS2

### ISSUE THREAD

**Issue by chan-hoo** [NOAA-EMC/rrfs-workflow#136]
- As python load is separate in the module files for wcoss2, some modules such as `PrgEnv-intel`, `craype`, and `intel` are loaded twice. 
- The python load should be merged into the main module file.

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA I'm going through old issues in rrfs-workflow and came across this one.  It looks like the python_srw module is loaded for every task, which means that the other modules inside python_srw (PrgEnv-intel, craype, intel) are indeed loaded twice.  Would a good solution be to eliminate python_srw and simply move the Python module loading into each individual task's modulefile?  It looks like at the start of each task, modules are reset to the system default, then the individual task modulefile is loaded.

**Comment by MatthewPyle-NOAA** [comment]
Eliminating python_srw sounds good to me - will this just be for production/RRFS.v1?

**Comment by BenjaminBlake-NOAA** [comment]
Okay sounds good, and yes I'll just do it for production/RRFS.v1.
