### ISSUE TITLE
Ensure static libraries are used in compiling

### ISSUE THREAD

**Issue by chan-hoo** [NOAA-EMC/rrfs-workflow#144]
- While compiling the app on wcoss2, cmake uses the dynamic libraries (.so) rather than the static ones (.a).
- We need to have cmake only use the static libraries.

**Comment by MatthewPyle-NOAA** [comment]
From recent WCOSS2 training:

"The default is to build dynamic executables with ftn and cc – static executables are no longer supported. "

So making this enhancement doesn't sound like a good idea.  Hopefully won't seem so necessary with the library debacle behind us (fingers crossed).

**Comment by chan-hoo** [comment]
@MatthewPyle-NOAA, thanks for the info. I'll have to take the training again :)
