### ISSUE TITLE
App does not build with the recent update on Orion

### ISSUE THREAD

**Issue by chan-hoo** [NOAA-EMC/rrfs-workflow#145]
- After PR #142 (v.0.7.7), the app does not build on Orion 
- The module file for Orion should be updated.

**Comment by guoqing-noaa** [comment]
@chan-hoo I am working on this and should have it ready soon.  Do you want me to continue and create a PR on this?

**Comment by chan-hoo** [comment]
@guoqing-noaa, thanks! yes, please go ahead.

**Comment by chan-hoo** [comment]
@JiliDong-NOAA, since all the external packages are compiled with one (integrated) module file, it would not work correctly. We should check the module list of GSI, UPP, UFS_UTILS, and RRFS-UTL as well. If each component is compiled separately, we can use the module file in its repository.

**Comment by JiliDong-NOAA** [comment]
> @JiliDong-NOAA, since all the external packages are compiled with one (integrated) module file, it would not work correctly. We should check the module list of GSI, UPP, UFS_UTILS, and RRFS-UTL as well. If each component is compiled separately, we can use the module file in its repository.

thanks for the explanation Chan-Hoo. What if there is module conflict/inconsistency between these components? should we use separate modules for each component instead of an integrated module for everything? BTW, my impression is that UFS_UTILS, UPP and ufs-weather-model always have (or are intended to use) the consistent modules.

**Comment by guoqing-noaa** [comment]
@JiliDong-NOAA Yes, as @chan-hoo mentioned, rrfs-workflow needs more libraries from spack-stack than ufs-weather-model.
The latest ufs-weather-model in rrfs-workflow uses spack-stack v1.5.0 where some libraries are missing and some libraries are at  different versions and hence GSI cannot compile or run. At the same time, spack-stack v1.5.1 can compile GSI but cannot compile the current ufs-weather-model in rrfs-workflow.

**Comment by chan-hoo** [comment]
@JiliDong-NOAA, I forgot to mention this. However, we can use only one version for each module on WCOSS2. It should be controlled in the file `version/run.ver`. So... it might not be easy to use multiple versions in one application.

**Comment by JiliDong-NOAA** [comment]
thanks again @guoqing-noaa and @chan-hoo for the discussion! I only raise the question because this is something I have struggled with since srw app. Glad to hear more options are being considered. :-)
