### ISSUE TITLE
Make grid error

### ISSUE THREAD

**Issue by ericaligo-NOAA** [NOAA-EMC/rrfs-workflow#154]
Not sure why no arguments were passed to the script file.
+ valid_args=()
+ process_args valid_args
+ return
+ print_input_args valid_args

No arguments have been passed to the script in file

  "/scratch1/NCEPDEV/fv3-cam/Eric.Aligo/save/rrfs-workflow_12072023/scripts/exrrfs_make_grid.sh"

**Comment by chan-hoo** [comment]
This is caused by the following part in `ush/link_fix.sh`:
```
    if [ "${PREDEF_GRID_NAME}" = "RRFS_CONUS_3km" ] || [ "${PREDEF_GRID_NAME}" = "RRFS_NA_3km" ]; then
      fns+=( \
      "C*${DOT_OR_USCORE}fvcom_mask.nc" \
           )
    fi
```
This is not necessary for non-DA.
