### ISSUE TITLE
Dust/smoke files for NA domain not linked/copied to INPUT directory and dt_atmos = 60

### ISSUE THREAD

**Issue by ericaligo-NOAA** [NOAA-EMC/rrfs-workflow#157]
The field_table contains the smoke/dust fields, however, none of the necessary files related to these fields are located in the INPUT directory. Some or all of them are grid-dependent.

dust12m_data.nc
emi_data.nc
SMOKE_RRFS_data.nc

Additionaly, dt_atmos is set to 60s, when it should be set to 36s.

**Comment by BenjaminBlake-NOAA** [comment]
It looks like the dust12m_data.nc and emi_data.nc files are now linked to the INPUT directories, and dt_atmos is correctly set to 36 instead of 60.  I'm going to close this issue.
