### ISSUE TITLE
DA engineering test fails on Hera due to missing input data

### ISSUE THREAD

**Issue by chan-hoo** [NOAA-EMC/rrfs-workflow#180]
The DA engineering test fails on Hera. This is because some input data files are missing after the change in PR #163. Need to update the configure file `config.DA.retro.hera.sh` with the sample script `config.sh.rrfs_b_c3`.

**Comment by chan-hoo** [comment]
@guoqing-noaa, @hu5970, I am trying to run the sample script `ush/sample_configs/config.sh.rrfs_b_c3` on Hera, but it fails due to some missing files such as gfs grib2 input data and fvcom files. Can you copy the necessary files for this sample run from Jet to Hera?

**Comment by guoqing-noaa** [comment]
@chan-hoo What specific files are missing? Can you share a copy of the error message? Thanks!

**Comment by chan-hoo** [comment]
@guoqing-noaa, I ran two cases: 1) 2023120100 (gfs data do not exist on hera) 2) 20230613 (gfs data exist on hera)
1) /scratch2/NCEPDEV/stmp3/Chan-hoo.Jeon/test_da_1201/logs/rrfs.20231201/00/get_extrn_lbcs_c0v00_2023120100.log
2) /scratch2/NCEPDEV/stmp3/Chan-hoo.Jeon/test_da/logs/rrfs.20230613/04/prep_cyc_spinup_c0v00_2023061304.log
I'd like to run the first case on Hera (2023120100) as a new DA engineering test.

**Comment by guoqing-noaa** [comment]
@chan-hoo 2023120100 is not within the [RRFS retro periods](https://docs.google.com/spreadsheets/d/1nBBxYld46DjDCTWr5Xh8u_F3i75bD10mAlh-pYQHKAg/edit#gid=1320841463).

We can download the required data from HPSS and save them somewhere.

**Comment by chan-hoo** [comment]
@guoqing-noaa, the cycle dates of the sample script `config.sh.rrfs_b_c3` are:
```
DATE_FIRST_CYCL="20231201"
DATE_LAST_CYCL="20231230"
```
I wonder why this sample runs out of the range.
In addition, according to the sheet, 20220720 (current cycle date of the DA eng test) is within the period. However, the input data files for this date are not found on Hera either.

**Comment by guoqing-noaa** [comment]
@chan-hoo 2022 Spring and summer data were removed recently to save disk space for 2023 retros.

If DA eng tests would like to use RRFS retro data in the future, you may want to be added to the email loop about RRFS retro data changes.  Or we may want to set up a test dataset separate from RRFS retro data.

**Comment by guoqing-noaa** [comment]
@chan-hoo To clarify, the changes breaking the DA eng test were brought by pull request #163

**Comment by chan-hoo** [comment]
@guoqing-noaa, got it. I'll test with the 2023 spring data. (and thanks for the clarification. updated!).

**Comment by chan-hoo** [comment]
@guoqing-noaa, the 2023 spring data (20230423) do not exist on hera either. The sheet needs to be updated. I am testing with 2023 spring/severe data (20230611) now.

**Comment by chan-hoo** [comment]
@guoqing-noaa, I got the following error:
```
+ 1 + message_txt='WARNING: No FVCOM data is available.'
+ 1 + print_info_msg 'WARNING: No FVCOM data is available.'
WARNING: No FVCOM data is available.
+ 1 + '[' '!' -z '' ']'
+ 1 + siglay0_tmp1=erie_siglay0_missing.nc
+ 1 + siglay0_tmp2=lmhofs_siglay0_missing.nc
+ 1 + siglay0_tmp3=sup_siglay0_missing.nc
+ 1 + siglay0_tmp4=ont_siglay0_missing.nc
+ 1 + ilake=1
+ 1 + ilake_use=0
/scratch2/NCEPDEV/fv3-cam/Chan-hoo.Jeon/rrfs_daeng/rrfs-workflow/scripts/exrrfs_prep_fvcom.sh: line 197: output_erie: unbound variable
```
```
/scratch2/NCEPDEV/stmp3/Chan-hoo.Jeon/test_da/logs/rrfs.20230611/04/prep_cyc_spinup_c0v00_2023061104.log
```
Can you copy the FVCOM data for 20230611 to Hera?

**Comment by guoqing-noaa** [comment]
@chan-hoo FVCOM data is available but in a slightly different file path pattern than what is required by `exrrfs_prep_fvcom.sh`. 
`/scratch2/BMC/zrtrr/RRFS_RETRO_DATA/fvcom/
`
I think @hu5970 may update this part in the next few days/weeks.

For now, you can set `USE_FVCOM="FALSE"` in the config file to bypass the FVCOM functionality.

**Comment by chan-hoo** [comment]
@guoqing-noaa, I got the following error at `09z`:
```
+ 35 + '[' -r /scratch2/NCEPDEV/stmp3/Chan-hoo.Jeon/test_da/nwges/2023061021/lbcs/gfs_bndy.tile7.036.nc ']'
+ 35 + err_exit 'Cannot find boundary file: /scratch2/NCEPDEV/stmp3/Chan-hoo.Jeon/test_da/nwges/2023061021/lbcs/gfs_bndy.tile7.036.nc'

--------------------------------------------------------------- 
FATAL ERROR: Cannot find boundary file: /scratch2/NCEPDEV/stmp3/Chan-hoo.Jeon/test_da/nwges/2023061021/lbcs/gfs_bndy.tile7.036.nc
-- ABNORMAL EXIT at Tue Jan  2 18:05:13 UTC 2024 on h21c01
-------------------------------------------------------------
```
Which parameters should I adjust in `config.sh` to resolve this issue? 
```
/scratch2/NCEPDEV/stmp3/Chan-hoo.Jeon/test_da/logs/rrfs.20230611/09
```
config.sh:
```
/scratch2/NCEPDEV/fv3-cam/Chan-hoo.Jeon/rrfs_daeng/expt_dirs/rrfs_test_da/config.sh
```

**Comment by guoqing-noaa** [comment]
@chan-hoo 
You can extend the boundary hours to 30:
`BOUNDARY_LEN_HRS="30"
`

Or:  since this is an engineering DA test, you may set the following two variables to 0:
```
EXTRN_MDL_ICS_OFFSET_HRS="0"
EXTRN_MDL_LBCS_OFFSET_HRS="0"
```

**Comment by chan-hoo** [comment]
@guoqing-noaa, if the above two variables are set to 0, the input grib2 data for `03z` don't exist in the grib2 directory:
```
/scratch2/BMC/zrtrr/RRFS_RETRO_DATA/gfs/0p25deg/grib2
```

**Comment by guoqing-noaa** [comment]
@chan-hoo You are right. We don't have input grib2 data for ` EXTRN_MDL_ICS_OFFSET_HRS="0"` 
Could you repeat the previous error at 09z?  I cannot find the error log file under 
`/scratch2/NCEPDEV/stmp3/Chan-hoo.Jeon/test_da/logs/rrfs.20230611/09
`

**Comment by chan-hoo** [comment]
@guoqing-noaa, I am running it again with
```
EXTRN_MDL_ICS_OFFSET_HRS="3"
EXTRN_MDL_LBCS_OFFSET_HRS="0"
```
I'll let you know what happens soon.

**Comment by guoqing-noaa** [comment]
@chan-hoo Sorry that `EXTRN_MDL_LBCS_OFFSET_HRS="6"` is not the cause of your previous error.

The problem lies in this line (around line 93):
`for i in {0..23..3}; do FCST_LEN_HRS_CYCLES[$i]=24; done
`

You can comment out this line so that every cycle only makes a 9h forecast. or Change it to:
for i in {0..23..**12**}; do FCST_LEN_HRS_CYCLES[$i]=24; done

**Comment by chan-hoo** [comment]
Got it. Thanks. I'll try it again.
