### ISSUE TITLE
Make changes so the proper real-time RRFS ICs are sent to AWS

### ISSUE THREAD

**Issue by MatthewPyle-NOAA** [NOAA-EMC/rrfs-workflow#194]
It came up that the ICs on AWS are from before the recentering step is done.  Need changes so both pre- and post-recentering ICs are saved to $COMOUT, with the post-recentering ICs then transferred to AWS.

**Comment by ShunLiu-NOAA** [comment]
Local changes were made in v0.7.7.  Post-recentering ICs are saved to /lfs/f2/t2o/ptmp/emc/ptmp/emc.lam/rrfs/v0.7.7/nwges/2024011706/mem0001/fcst_fv3lam_enfcst/DA_OUTPUT since 00z cycle on 20240117.

**Comment by MatthewPyle-NOAA** [comment]
I think in a perfect world we'd send both, but given our space constraints on AWS I'd say just the post-recentering ICs.  Looping in @JacobCarley-NOAA for confirmation.

**Comment by JacobCarley-NOAA** [comment]
Yes - post recenter ICs are the correct ones.

**Comment by BenjaminBlake-NOAA** [comment]
Thanks for confirming.  The transfer scripts have been modified so I'll go ahead and close this issue.
