### ISSUE TITLE
GET_GEFS_LBCS_FILES task loads modules in ex-script

### ISSUE THREAD

**Issue by chan-hoo** [NOAA-EMC/rrfs-workflow#195]
Currently, the `GET_GEFS_LBCS_FILES` task loads the necessary modules in its ex-script. The modules should be loaded in the job-card level. (job card > J-job > ex-script)

**Comment by BenjaminBlake-NOAA** [comment]
Closing this issue because the GET_GEFS_LBCS_FILES task no longer exists.  This was resolved with PR #278
