### ISSUE TITLE
Some python scripts in scripts dir should be moved to ush

### ISSUE THREAD

**Issue by chan-hoo** [NOAA-EMC/rrfs-workflow#21]
- Two python scripts `fvcom_remap.py` and `preprocess_smoke.py` are located in the ex-script directory `scripts`. They should be moved into the `ush` directory.

**Comment by chan-hoo** [comment]
@MatthewPyle-NOAA, as can be seen in jobs and scripts, the task `process_smoke` doesn't have its own ex-script but uses a python script directly in the scripts directory. Is this acceptable?

**Comment by MatthewPyle-NOAA** [comment]
@chan-hoo Just seeing this one now.  Do you mean the J-job is calling a python script (in the scripts/ kind of space)?  If so, that would be okay.  But the fvcom_remap.py script does seem like more of a ush utility script.  I can take a look at the code to understand it better.
