### ISSUE TITLE
Separate blending step from make_ics to improve runtime efficiency

### ISSUE THREAD

**Issue by delippi** [NOAA-EMC/rrfs-workflow#215]
Right now, we have the chgres_cube and the entire blending (and pre-blending) steps combined in the make_ics task. The blending and pre-blending consists of the cold2warm step, a vertical remapping step, and finally the actual blending step. How it is currently formulated, make_ics takes about 1000s to run and must also wait until the regional ensemble is available. If you look at how it breaks down, the chgres_cube itself takes about 260s, the cold2warm and vertical remap step takes another 370s, and the blending step takes another 430s. There isn't a technical reason why all of these steps have to be in the make_ics task. Technically, only the blending step depends on the existence of the regional ensemble. The rest of the make_ics task (chgres_cube, cold2fv3, and vertical remapping) could all be run earlier even before the regional ensemble is available.

**Comment by MatthewPyle-NOAA** [comment]
This has been merged...closing issue.
