### ISSUE TITLE
Check that the J-job, ex-script, ush script hierarchy is good throughout

### ISSUE THREAD

**Issue by MatthewPyle-NOAA** [NOAA-EMC/rrfs-workflow#242]
Make sure that no J-jobs directly call a ush script (should either be an intervening ex-script, or the ush script should be an ex-script)

Make sure that utility scripts (scripts called by another script) are in ush

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA Can this issue be closed?  There are no ush scripts being called by J-jobs, and all utility scripts are in ush.  The only question I have is whether exrrfs_process_lightning.py (exrrfs_process_glmfed.py) in the scripts directory needs to have an associated ex-script, and the Python script moved into ush.

**Comment by MatthewPyle-NOAA** [comment]
I think closing it is fine.  Thanks for confirming.
