### ISSUE TITLE
Look to utilize the new stochastic_physics flexibility

### ISSUE THREAD

**Issue by MatthewPyle-NOAA** [NOAA-EMC/rrfs-workflow#246]
Confirm that it has been scientifically validated (it has - see below), then look to add it into the workflow to speed up the ensemble forecasts significantly (10-20%?).  Figure out what needs to be added to input.nml or model_configure to make it happen.

**Comment by JacobCarley-NOAA** [comment]
@JiliDong-NOAA [validated it here](https://docs.google.com/presentation/d/1EC2wftp4yW8BZqc0v9ZzqvM7Mpu13H1Z/edit?usp=sharing&ouid=108910029632374208476&rtpof=true&sd=true)

**Comment by MatthewPyle-NOAA** [comment]
@JiliDong-NOAA - can you provide what needs to be added to the input.nml or model_configure file to utilize this functionality?

**Comment by JiliDong-NOAA** [comment]
> @JiliDong-NOAA - can you provide what needs to be added to the input.nml or model_configure file to utilize this functionality?

To call SPP every hour, just add:

`    lndpint = 3600`
in &nam_sfcperts block 

`    sppint = 3600`
in &nam_sppperts block

for ensemble input.nml.

**Comment by MatthewPyle-NOAA** [comment]
Thanks @JiliDong-NOAA !

**Comment by MatthewPyle-NOAA** [comment]
Will open a PR for this issue...my initial attempt appears to have added the needed items to the ensemble input.nml files:


&nam_sfcperts 
    iseed_lndp = 9
    lndp_lscale = 150000, 150000, 150000, 150000, 150000
    lndp_model_type = 2
    lndp_prt_list = 0.2, 0.001, 0.001, 0.001, 0.001, 0.001, 0.2
    lndp_tau = 21600, 21600, 21600, 21600, 21600
    lndp_type = 2
    lndp_var_list = 'smc', 'vgf', 'alb', 'sal', 'emi', 'zol', 'stc'
    **lndpint = 3600**
/   
    
&nam_sppperts 
    iseed_spp = 4, 5, 6
    spp_lscale = 150000.0, 150000.0, 150000.0
    spp_prt_list = 0.2, 0.2, 0.3
    spp_sigtop1 = 0.1, 0.1, 0.1
    spp_sigtop2 = 0.025, 0.025, 0.025
    spp_stddev_cutoff = 1.5, 1.5, 3.0
    spp_tau = 21600.0, 21600.0, 21600.0
    spp_var_list = 'rad', 'gwd', 'cu_deep'
    **sppint = 3600**
/
