### ISSUE TITLE
Task name changes from 'verb-like' to 'noun-like' to remove 'run_' prefix

### ISSUE THREAD

**Issue by BenjaminBlake-NOAA** [NOAA-EMC/rrfs-workflow#247]
Carrying this issue over from the SRW app: https://github.com/ufs-community/ufs-srweather-app/issues/633

It makes sense to keep some verb prefixes attached to the RRFS tasks to keep them somewhat descriptive.  However, the run_* prefix should be removed, as it is superfluous and does not provide much added value.  Here are the suggested names for the RRFS tasks (these can be modified):

make_grid (no change)
make_orog (no change)
make_sfc_climo (no change)
make_ics (no change)
blend_ics (no change)
make_lbcs (no change)
calc_ensmean (no change)
process_smoke (no change)
save_restart (no change)
save_da_output (no change)
process_bufr ---> no change

run_prepstart ---> prep_cyc
process_radarref ---> process_radar
process_glmfed ---> process_lightning or no change (there used to be another process_lightning task but that one was removed)
run_analysis ---> analysis_gsi, 
run_gsidiag ---> analysis_gsidiag
run_enkf ---> analysis_enkf
run_nonvarcldanl ---> analysis_nonvarcld
run_recenter -> recenter
run_postanal ---> update_lbc_soil (postanalysis is not good because post typically refers to running the UPP)
run_fcst -> forecast
run_post -> post
run_prdgen -> prdgen
run_bufrsnd -> bufrsnd

**Comment by ShunLiu-NOAA** [comment]
The changes looks good to me.
