### ISSUE TITLE
Engineering test forecasts failing on WCOSS2 (and likely everywhere)

### ISSUE THREAD

**Issue by MatthewPyle-NOAA** [NOAA-EMC/rrfs-workflow#291]
Problem traced back to the change to nsponge=65 with Kevin's streak fix, as the engineering tests are running with an old 64 level configuration.  

make nsponge=64 for engineering tests, or (preferably) update the engineering tests to be in line with the 65 levels of RRFS.

**Comment by BenjaminBlake-NOAA** [comment]
Resolved by PR #293
