### ISSUE TITLE
Establish a dev-sci branch that reproduces answers from current RRFS_dev1 system

### ISSUE THREAD

**Issue by MatthewPyle-NOAA** [NOAA-EMC/rrfs-workflow#3]
First board item

**Comment by aerorahul** [comment]
Note:
`develop` has been renamed to `dev-sci`.
Branch protections are enabled on `dev-sci`.  All pushes need to be as part of a PR.

**Comment by MatthewPyle-NOAA** [comment]
Thanks for the rename, @aerorahul

**Comment by ShunLiu-NOAA** [comment]
We should let GSL start to use dev-sci branch ASAP.
