### ISSUE TITLE
Sort out issues with 15 minute accumulated precip records

### ISSUE THREAD

**Issue by MatthewPyle-NOAA** [NOAA-EMC/rrfs-workflow#304]
May post the same issue in the UPP repository.  

```
 wgrib2 rrfs.t12z.prslev.f003.conus_3km.grib2 -match APCP
820:737929943:d=2024040212:APCP:surface:2-3 hour acc fcst: (max 29.375)
821:738016911:d=2024040212:APCP:surface:0-3 hour acc fcst: (max 41.9375)

wgrib2 rrfs.t12z.prslev.f003-15-00.pr.grib2 -match APCP
820:59191477:d=2024040212:APCP:surface:10815--2147472656 min acc fcst: (max 626.188)
821:59199007:d=2024040212:APCP:surface:15-18 min acc fcst: (max 38.6875)

wgrib2 rrfs.t12z.prslev.f003-30-00.pr.grib2 -match APCP
820:59587233:d=2024040212:APCP:surface:10830--2147472641 min acc fcst: (max 842.375)
821:59596225:d=2024040212:APCP:surface:30-33 min acc fcst: (max 44.5)


```
The run time total (second APCP record) mostly seems to be okay (though the run total drops between f03 and f03:15), but is mislabeled in the 15 minute output.   Maybe when we trim down the 15 minute product list, can eliminate this partial bucket record if remains problematic.

**Comment by MatthewPyle-NOAA** [comment]
More updates...sub hourly product (running total) all zero within first hour.   Running total drops from 1:15 to 1:30 into forecast.   Problematic time labels for all of the subhourly 

```
wgrib2 -V rrfs.t06z.prslev.f000-15-00.conus.grib2 -match APCP
19:18445403:vt=2024041106:surface:15-15 min acc fcst:APCP Total Precipitation [kg/m^2]:
    ndata=1905141:undef=0:**mean=0:min=0:max=0**

wgrib2 -V rrfs.t06z.prslev.f000-30-00.conus.grib2 -match APCP
19:18474763:vt=2024041106:surface:30-30 min acc fcst:APCP Total Precipitation [kg/m^2]:
    ndata=1905141:undef=0:**mean=0:min=0:max=0**

wgrib2 -V rrfs.t06z.prslev.f000-45-00.conus.grib2 -match APCP
19:18543802:vt=2024041106:surface:45-45 min acc fcst:APCP Total Precipitation [kg/m^2]:
    ndata=1905141:undef=0:**mean=0:min=0:max=0**

wgrib2 -V rrfs.t06z.prslev.f001.conus.grib2 -match APCP
758:643509165:vt=2024041107:surface:0-1 hour acc fcst:APCP Total Precipitation [kg/m^2]:
    ndata=1905141:undef=0:mean=0.132625:min=0:max=98.5625

wgrib2 -V rrfs.t06z.prslev.f001-15-00.conus.grib2 -match APCP
19:18736740:vt=2024041107:surface:15-16 min acc fcst:APCP Total Precipitation [kg/m^2]:
    ndata=1905141:undef=0:mean=0.134905:min=0:max=101.5

wgrib2 -V rrfs.t06z.prslev.f001-30-00.conus.grib2 -match APCP
19:18796085:vt=2024041107:surface:30-31 min acc fcst:APCP Total Precipitation [kg/m^2]:
    ndata=1905141:undef=0:mean=0.136489:min=0:max=91.5
```

**Comment by EricJames-NOAA** [comment]
@MatthewPyle-NOAA thanks for the info.  I see that we currently have these four 15-min acc variables in RRFS-A:

ASNOW
APCP
FRZR
TSNOWP

Can you confirm we need all of these?  Or do we just need APCP?

**Comment by MatthewPyle-NOAA** [comment]
@EricJames-NOAA  I'd say APCP is the only critical one - the others were on the "nice to have" pile, but I've been wondering if they should be trimmed.   HRRR has these accumulation fields...probably why I included some winter weather fields:

26:25857641:d=2024050114:APCP:surface:1020-1035 min acc fcst:
27:26245238:d=2024050114:WEASD:surface:1020-1035 min acc fcst:
28:26313753:d=2024050114:FROZR:surface:1020-1035 min acc fcst:

**Comment by EricJames-NOAA** [comment]
@MatthewPyle-NOAA thanks.  I'll include them for now, and we can decide to remove them later if we want.

**Comment by EricJames-NOAA** [comment]
@MatthewPyle-NOAA I have the UPP changes ready which are required to clean up the labeling.  Should I open a PR, or wait until we have the final bucket values to finalize the 15-min fields?  I guess there will be some minor UPP changes to pass through the correct bucket fields

**Comment by MatthewPyle-NOAA** [comment]
@EricJames-NOAA Definitely open a UPP PR for this fix.  That will motivate me to the finish the follow on work on a separate bucket code.

**Comment by MatthewPyle-NOAA** [comment]
The bug in 15 minute file QPF output was resolved - still some work if want to create 15 minute buckets.
