### ISSUE TITLE
Turn off special FAA grib2 output for ensemble forecasts

### ISSUE THREAD

**Issue by BenjaminBlake-NOAA** [NOAA-EMC/rrfs-workflow#333]
The following FAA files need the ensemble member number added to the filenames:

rrfs.t${cyc}z.aviati.f${fhr}.conus13km.grib2 -> rrfs.t${cyc}z.**m0?**.aviati.f${fhr}.conus13km.grib2
rrfs.t${cyc}z.ififip.f${fhr}.ak3km.grib2 -> rrfs.t${cyc}z.**m0?**.ififip.f${fhr}.ak3km.grib2
rrfs.t${cyc}z.ififip.f${fhr}.conus13km.grib2 -> rrfs.t${cyc}z.**m0?**.ififip.f${fhr}.conus13km.grib2
rrfs.t${cyc}z.prslevfaa.f${fhr}.conus13km.grib2 -> rrfs.t${cyc}z.**m0?**.prslevfaa.f${fhr}.conus13km.grib2
rrfs.t${cyc}z.prslevfaa.f${fhr}.na13km.grib2 -> rrfs.t${cyc}z.**m0?**.prslevfaa.f${fhr}.na13km.grib2
rrfs.t${cyc}z.prslevfaa.f${fhr}.pr32km.grib2 -> rrfs.t${cyc}z.**m0?**.prslevfaa.f${fhr}.pr32km.grib2

**Comment by MatthewPyle-NOAA** [comment]
@BenjaminBlake-NOAA Hold off on this one, I'm not sure if these files should be generated for the ensemble forecasts.

**Comment by MatthewPyle-NOAA** [comment]
Have confirmed that we don't need them for ensemble forecasts.  So maybe I'll change the title

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA  Sounds good.  It should be a relatively simple change to turn off the FAA processing for ensemble forecasts, so I can create a PR for this one shortly.

**Comment by BenjaminBlake-NOAA** [comment]
This issue was resolved with PR #353 .  I will incorporate this simple change into the production/RRFS.v1 branch with my next upcoming PR.
