### ISSUE TITLE
Flash extent density preprocessing should apply the high-flash cutoff consistently

### ISSUE THREAD

**Issue by AmandaBack-NOAA** [NOAA-EMC/rrfs-workflow#344]
Flash extent density preprocessing can read full-disk data or tiled data. In the full disk preprocessing, flash rates higher than 8/minute are truncated to 8 because the correlation between flash rates and simulated graupel became weak above that limit in our calibration data. However, the truncation was not applied to the tile preprocessors that were added later. The truncation should be added.

This will not affect RRFS results because the truncation is applied again in GSI.

**Comment by MatthewPyle-NOAA** [comment]
Believe this was resolved by [your PR](https://github.com/NOAA-EMC/rrfs-workflow/pull/345) - safe to close?
