### ISSUE TITLE
Unify file name standards in response to EE2 kickoff meeting recommendations

### ISSUE THREAD

**Issue by MatthewPyle-NOAA** [NOAA-EMC/rrfs-workflow#351]
1) include grid spacing for products where it isn't currently included
2) Add a "na" domain descriptor for the full domain products
3) confirm that we are matching these conventions (pretty sure we have it correct even though NCO said we didn't)

deterministic: `model.tHHz.var_info.f###.domain.format`
ensemble:      `model.tHHz.ens_mem.var_info.f###.domain.format`

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA It looks like the variable names conventions are correct in our files, not sure why NCO thought we had it wrong.

For #2 that will be straightforward to add: rrfs.t00z.prslev.f024.grib2 -> rrfs.t00z.prslev.f024.na.grib2
But for adding the grid spacing, where should that go?  Some possibilities:
rrfs.t00z.prslev.3km.f024.na.grib2 (in GFS filenames, 0p25 comes after pgrb2 and before forecast hour: gfs.t00z.pgrb2.0p25.f060)
rrfs.t00z.prslev.f024.na_3km.grib2 (similar to what we used to do for conus_3km)

**Comment by MatthewPyle-NOAA** [comment]
@BenjaminBlake-NOAA I think rrfs.t00z.prslev.3km.f024.na.grib2 is the best option.  Both prslev and 3km are part of the "var info" section of the file, and subpieces of that information are supposed to be separated with periods.

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA Sounds good to me.  I should be able to get this one done fairly quickly and will try and run a quick test before submitting a PR.

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA One more quick question - for the firewx nest, which is on a 1.5 km grid, is it acceptable to have a period for 1.5km or is there a better way to handle that since periods are already used for the other delimiters?
rrfs.t00z.prslev.1.5km.f024.firewx.grib2

**Comment by BenjaminBlake-NOAA** [comment]
The GFS has 0p25 for quarter degree grids so maybe 1p5km would work

**Comment by MatthewPyle-NOAA** [comment]
Yes, 1p5km would be correct (since the "." is used to delimit different sections of the filename).
