### ISSUE TITLE
Remove smoke and dust GRIB output from ensemble member and firewx output

### ISSUE THREAD

**Issue by MatthewPyle-NOAA** [NOAA-EMC/rrfs-workflow#357]
Even though smoke and dust aren't running beyond the deterministic system, the ensemble and firewx pieces are writing 0-value MASSDEN, AEMFLX, and COLMD type fields to GRIB output.  Something to clean up - confused me when answering the EVS people about what components of RRFSv1 are generating smoke and dust.

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA  That works for me!

**Comment by BenjaminBlake-NOAA** [comment]
This issue was resolved with PR #361
