### ISSUE TITLE
one line bug fix to RUCLSM

### ISSUE THREAD

**Issue by hu5970** [NOAA-EMC/rrfs-workflow#374]
The lowest level of the soil temperature in RUCLSM will be from climate instead of high resolution RRFS.
To fix this bug, one line in RUCLSM need to be removed:

```
FV3/ccpp/physics/physics/SFC_Models/Land/RUC

--- a/physics/SFC_Models/Land/RUC/module_sf_ruclsm.F90
+++ b/physics/SFC_Models/Land/RUC/module_sf_ruclsm.F90
@@ -1077,8 +1077,6 @@ CONTAINS
                   tso(i,k,j) = tso1d(k)
         enddo
 
-        tso(i,nzs,j) = tbot(i,j)
-
         do k=1,nzs
              smfr3d(i,k,j) = smfrkeep(k)
            keepfr3dflag(i,k,j) = keepfr (k)
```

**Comment by MatthewPyle-NOAA** [comment]
@hu5970 How critical is this one?  What kind of impact does fixing it have?  Not inclined to unfreeze the system unless fixing this issue makes things dramatically better.

**Comment by MatthewPyle-NOAA** [comment]
This was fixed in UFS WM (https://github.com/ufs-community/ufs-weather-model/pull/2343) back in July.  Closing.
