### ISSUE TITLE
Problems with dev-sci compilation of model on Hera (& WCOSS2)

### ISSUE THREAD

**Issue by MatthewPyle-NOAA** [NOAA-EMC/rrfs-workflow#380]
Seeing this issue compiling the latest rrfs-workflow on Hera...have you seen anything similar, @hu5970 ?

 tail -n15 log.make
[ 96%] Building Fortran object FV3/CMakeFiles/fv3atm.dir/io/module_write_restart_netcdf.F90.o
[ 96%] Building Fortran object FV3/CMakeFiles/fv3atm.dir/io/post_fv3.F90.o
[ 97%] Building Fortran object FV3/CMakeFiles/fv3atm.dir/io/module_wrt_grid_comp.F90.o
[ 98%] Building Fortran object FV3/CMakeFiles/fv3atm.dir/io/fv3atm_restart_io.F90.o
[ 99%] Building Fortran object FV3/CMakeFiles/fv3atm.dir/atmos_model.F90.o
/scratch2/NCEPDEV/fv3-cam/Matthew.Pyle/rrfs-workflow/sorc/ufs-weather-model/FV3/atmos_model.F90(52): error #6580: Name in only-list does not exist or is not accessible.   [CLOSE_FILE]
use fms_mod,            only: close_file, write_version_number, stdlog, stdout
------------------------------^
compilation aborted for /scratch2/NCEPDEV/fv3-cam/Matthew.Pyle/rrfs-workflow/sorc/ufs-weather-model/FV3/atmos_model.F90 (code 1)
make[5]: *** [FV3/CMakeFiles/fv3atm.dir/build.make:75: FV3/CMakeFiles/fv3atm.dir/atmos_model.F90.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:385: FV3/CMakeFiles/fv3atm.dir/all] Error 2
make[3]: *** [Makefile:136: all] Error 2
make[2]: *** [CMakeFiles/ufs-weather-model.dir/build.make:86: ufs-weather-model/src/ufs-weather-model-stamp/ufs-weather-model-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:883: CMakeFiles/ufs-weather-model.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by MatthewPyle-NOAA** [comment]
Was able to sidestep the problem by avoiding use of the fms/2024.01 library and avoiding the parallel enhancements from GDIT.

**Comment by hu5970** [comment]
Here are two lines of changes needed to make it work:

<img width="1487" alt="Screenshot 2024-05-30 at 12 50 35 PM" src="https://github.com/NOAA-EMC/rrfs-workflow/assets/7036270/79a8d74a-fe13-4a30-a316-c0809b99c8f3">

**Comment by MatthewPyle-NOAA** [comment]
Thanks @hu5970.  I finally was able to compile and run with the official fms/2024.01 on acorn, and it worked without this code change.  But not sure how quickly the official fms/2024.01 will be placed on the full WCOSS.
