### ISSUE TITLE
Add error checking/logging/alerting to the workflow scripts

### ISSUE THREAD

**Issue by BenjaminBlake-NOAA** [NOAA-EMC/rrfs-workflow#39]
Whenever a script or part of a script fails, we should be notified somehow.  I believe this can be done using the err_chk and err_exit functions from the prod_util module.

**Comment by JacobCarley-NOAA** [comment]
Recommend making this specific to alerting relative to when  non-fatal errors are encountered. This happens with input files upon which we have an external dependency. For example, fvcom lake data are one such input where the system should run if the files are absent but developers should be alerted and event logged.
