### ISSUE TITLE
Meet NCO Standard - using production utility prep_step

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/rrfs-workflow#404]
Review jobs and replace the use of "rm -f 'fort.*' " with production utility prep_step.

**Comment by BenjaminBlake-NOAA** [comment]
@lgannoaa @MatthewPyle-NOAA  Does prep_step actually remove the fort* files?  According to the implementation standards doc, it unsets the FORT environment variables, but I didn't think it deleted them.  I found two instances of "rm -f fort.*" within the RRFS ex-scripts, one is in exrrfs_post.sh and the other is in exrrfs_bufrsnd.sh.  However within those scripts I also see prep_step is used further down before an executable is called.  I looked in the production AQM scripts and I do see "rm -f fort.*" is used in exaqm_post.sh, so maybe they don't need to be removed?  Just want to confirm my understanding here - thanks!

**Comment by lgannoaa** [comment]
Hi @BenjaminBlake-NOAA Thank you for your hard work. I was in AL these couple of days. The prep_step does not remove the fort* files. It only unset the FORT environment variables as you noticed. If the application logic using "rm -f fort.*", we need to exam the need for this action in detail. Implementation standard require the DATA be retained if KEEPDATA=YES in production. It needs to enable the developer to rerun the job using a driver on this same directory to reproduce output. Unconditional remove of fort will challenge this implementation standard by disable the rerun capability.

**Comment by BenjaminBlake-NOAA** [comment]
@lgannoaa Thanks for that information!  I think that KEEPDATA will likely be set to NO in production for the post and bufrsnd tasks but I could be wrong about that.  In any case I think the two instances of "rm -f fort*" can be safely removed, but I might not need to replace them with prep_step because that utility is called further down in each script.  I'll include this in an upcoming PR.

**Comment by lgannoaa** [comment]
Sound good to me. Appreciate your excellent work.

**Comment by BenjaminBlake-NOAA** [comment]
Issue has been resolved with PR #436
