### ISSUE TITLE
Meet NCO Standard - Review and remove unnecessary use of "wait" in scripts

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/rrfs-workflow#406]
Review and remove unnecessary use of "wait" in scripts. For example, exrrfs_run_prdgen.sh
 Line 463: has statement "wait"
 Line 466, 478 unconditionally cleanup files in DATA where it should eval "KEEPDATA" setup.

**Comment by BenjaminBlake-NOAA** [comment]
Issue has been resolved with PR #436
