### ISSUE TITLE
Add the ungrib task to the rrfs-mpas-jedi branch

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/rrfs-workflow#435]
#### The following NCO-side changes will be made:  
1. add `jobs/JRRFS_UNGRIB`  
2. add `scripts/exrrfs_ungrib.sh`  
3. add `fix/` 
4. add `parm/`
5. add `parm/config/`
6. add `modulefiles/`
7. add `sorc/`, `sorc/build.wps`, `sorc/build.all`

#### The following non-NCO-side changes will be made:
1. modify `.gitignore`
2. add `workflow/setup_rocoto.py` which will be used to set up different experiments and create rocoto XML files.   
3. add `workflow/rocoto_funcs/` which provides Python functions for `setup_rocoto.py`  
4. add `util/sideload/` which provides a `launch.sh` script to mimic some preparation work in an ecflow job card and also host any tasks that definitely will NOT go into operation ( such as `clean`, `archive`, etc)
5. add `util/detect_machines.sh`, `util/init.sh`, and some data stage utils

**Comment by guoqing-noaa** [comment]
I have two questions:
1. To my superficial understanding of the NCO implementation standards, files under `parm/` should be parameterized files that will be used to, such as, generate namelist files on-the-fly.  In my current work, all config files are fixed (but flexible enough for different machines, tasks, etc). So I am not sure where to put these config files. It will be good if NCO allows them under `parm/config`.  If not, maybe we can put them under `util/config`  
2.  I separate resource configurations from the rrfs runtime configuration. Resource configurations are only needed in the experiment setup process and NOT needed in the rrfs runtime. [More details can be found here](https://github.com/NOAA-EMC/rrfs-workflow/wiki/The-cascade-config-structure). Currently, these config files are put under `config/resources` and will not be copied to the final experiment directory. Similar to Question 1, not sure whether NCO will accept this arrangement. 

@MatthewPyle-NOAA @BenjaminBlake-NOAA  Could you provide some guidance? Thanks!

**Comment by BenjaminBlake-NOAA** [comment]
@guoqing-noaa For 1), I think putting them under the fix/ subdirectory makes the most sense.  util is not listed as one of the directories in the NCO implementation standards document.  Thanks!

I'm not sure about 2)

**Comment by BenjaminBlake-NOAA** [comment]
For 1) I wonder if it could also be acceptable to put them under parm/.  Some of the files currently in parm/ aren't modified at runtime, like the diag_table and field_table files.

**Comment by guoqing-noaa** [comment]
Thanks, @BenjaminBlake-NOAA

**Comment by lgannoaa** [comment]
@guoqing-noaa thank you for your contribution. I have a clarification question for you. Would you please help me to understand the second point:
"Currently, these config files are put under config/resources and will not be copied to the final experiment directory. Similar to Question 1, not sure whether NCO will accept this arrangement."
I am try to review the PR. Without full understanding of the initial point in this issue, it will be difficult to give guidance.

**Comment by guoqing-noaa** [comment]
@lgannoaa 
files under config/resources are only used in the generation of a rocoto workflow, they are not needed in the rrfs runtime.

Does this help? Or could you elaborate more about your question?

**Comment by guoqing-noaa** [comment]
@lgannoaa Also to be clear, we are not in the final stage of the rrfs(mpas) workflow. We are at the beginning stage. There should be some intermediate things in the current rrfs-mpas-jedi branch and they may be changed in a later stage.

**Comment by lgannoaa** [comment]
We understand some components are under development. We do prefer the design architecture comply with the implementation standard from the start.
