### ISSUE TITLE
Bug fix in rrfs_prdgen_faa_subpiece script

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/rrfs-workflow#440]
Script rrfs_prdgen_faa_subpiece.sh line 48:
if [ ${ifmn} -eq  ""]; then    # exact hour, hourly (eg. f012) generated run time error because the empty string was used.

**Comment by guoqing-noaa** [comment]
Good catch!  Finding this bug is not a trivial thing.
If we advocate using `[[` instead of `[` in the [rrfs-workflow code norm](https://github.com/NOAA-EMC/rrfs-workflow/wiki/rrfs%E2%80%90workflow-code-norm), we may avoid this bug:
```
if [[ ${ifmn} -eq "" ]]; then
  echo 'yes'
fi
```

**Comment by BenjaminBlake-NOAA** [comment]
@lgannoaa I think this issue was fixed in PR #443 that you created last week, so I'll go ahead and close it.  Thanks
