### ISSUE TITLE
`ush` vs `util`

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/rrfs-workflow#468]
In a previous meeting, we temporarily decided that we would like to split utilities into two parts;
1. `ush/` which holds all utilities that will be referenced by the rrfs-workflow in the run time
2. `util/` which holds all utilities that will NOT be referenced by the rrfs-workflow in the run time

But it looks like this `util/` directory will only be used by rrfs-workflow.

HAFS (https://github.com/ufs-community/HAFS/tree/develop/ush),  GFS(https://github.com/NOAA-EMC/global-workflow/tree/develop/ush), RDASApp(https://github.com/NOAA-EMC/RDASApp/tree/develop/ush) all use `ush/` to hold all kinds of utilities. 

In order to keep a consistent user experience, we may want to use only `ush/` similar to other systems.

**Comment by ShunLiu-NOAA** [comment]
![image](https://github.com/user-attachments/assets/f90f1da0-85b6-4bc5-af1c-916b61f98787)
@guoqing-noaa If you check RAP, HRRR and NAM in operation, we are doing very good job to keep "ush" for the scripts that are used for operation only.

**Comment by guoqing-noaa** [comment]
Thanks, @ShunLiu-NOAA 
That's good to know. I never get a look at operational RAP/HRRR.  
Although other systems do not adopt a similar practice yet, I personally think it is a good idea to have a separate `util/`.
