### ISSUE TITLE
add to readme description of what's in each directory

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/rrfs-workflow#504]
For the readme, what are the contents of the different subdirectories:
* ecf ?
* fix - some data files?
* jobs ?
* modulefiles - module files for NOAA HPC systems
* parm ?
* scripts?
* sorc ?
* tests - unit tests for rrfs-workflow code
* ush?
* versions - shell scripts setting environment vars to the required versions of all dependencies, for building and for running rrfs-workflow.

**Comment by MatthewPyle-NOAA** [comment]
scripts - the "ex scripts" - the primary script for a given task, and called by the J-job.

sorc - all of the source codes that need to be built/compiled for use within the package

ush - the utility scripts - scripts typically called by the "ex scripts" to handle specific tasks, often repeatedly for different times or geographic regions.

Want to bring in @BenjaminBlake-NOAA to see if he has any additional perspective to add.   And can point you at the NCO implementation standard (https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf) which describes most of these items in Table 3 on p. 19.

**Comment by BenjaminBlake-NOAA** [comment]
Thanks @MatthewPyle-NOAA and @edwardhartnett .  These descriptions sound pretty good to me.
