### ISSUE TITLE
clean up jobid definitions in J-jobs

### ISSUE THREAD

**Issue by MatthewPyle-NOAA** [NOAA-EMC/rrfs-workflow#525]
jobid/taskid defining has yet to be done consistently throughout the system.  This issue is to remind us to consistently apply a solution for all J-jobs.

**Comment by hu5970** [comment]
@BenjaminBlake-NOAA Thanks for working on this. I will run test after your make your PR.

**Comment by BenjaminBlake-NOAA** [comment]
@hu5970 Thank you, that sounds good to me.  I should have a PR ready later today or tomorrow.

**Comment by BenjaminBlake-NOAA** [comment]
@hu5970 I just created a draft PR with these changes here: #535 
Are you still able to help with testing?  I ran a quick DA engineering test and it completed successfully.

**Comment by MatthewPyle-NOAA** [comment]
@BenjaminBlake-NOAA can this issue be closed now?
