### ISSUE TITLE
[rrfs-mpas-jedi] UPP crashed

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/rrfs-workflow#528]
UPP run crashed with the following error:
```
Caught signal 11 (Segmentation fault: address not mapped to object at address 0x154a170833d0)
```
Here is one log file:
`/scratch1/BMC/wrfruc/gge/nco/com/conus12km/1.0.1/logs/rrfs.20240527/03/upp_f001_c1v01_2024052703.log`

@EricJames-NOAA Could you help check this issue?  Thanks!
If PR #527 is not merged at the time you start your work, please check out my fork.

**Comment by EricJames-NOAA** [comment]
@guoqing-noaa this looks similar to a crash that Trevor recently had with 1-km MPAS.  I think it has to do with CRTM.  I will dig into it.

**Comment by EricJames-NOAA** [comment]
@guoqing-noaa I confirmed this is the same issue Trevor was having.  It seems the problem is repeatable, but only affects certain forecast hours, so maybe it is related to meteorology.  There is a crash in CRTM.  

If we exclude the simulated satellite brightness temperature fields from the output, we can get rid of the crashes.  If you want to go this route, I can open a PR to update the UPP control files.  

There is also this PR being worked on for UPP, which could resolve the issue:

https://github.com/NOAA-EMC/UPP/pull/1062

**Comment by guoqing-noaa** [comment]
@EricJames-NOAA Thanks a lot for digging into this! 

I would think, for the moment, it is okay to exclude the BT output in grib2 files. 

@HaidaoLin-NOAA Do you have any thoughts on this?

**Comment by HaidaoLin-NOAA** [comment]
@guoqing-noaa I think we can exclude the BT output in grid2 files for now and we can re-visit/test this after the above UPP/CRTM issue is fixed.

**Comment by guoqing-noaa** [comment]
Thanks @HaidaoLin-NOAA 

@EricJames-NOAA Could you go ahead to open a new PR to solve the UPP crash as discussed? Thanks!

**Comment by EricJames-NOAA** [comment]
@SamuelDegelia-NOAA thanks for looking into this.  I cannot remember why I reinstated those brightness temperature fields, but I can remove them again.  

I may also reach out to folks at the University of Wisconsin to see if they have any advice about getting past this crash, or any other modifications for brightness temperature output that we might need.

**Comment by HaidaoLin-NOAA** [comment]
@SamuelDegelia-NOAA it looks like I also had a few upp crashes for 12km runs, seems also related to crtm.  Could you please share with me your new postxconfig-NT.txt file?  Also, do we need to make any changes to mpas_hrrr_postcntrl.xml if we change the postxconfig-NT.txt file? Thanks!     @EricJames-NOAA  It looke like you also updated the mpas_hrrr_postcntrl.xml  file when you removed the bt variables from postxconfig-NT.txt ? Thanks!

**Comment by HaidaoLin-NOAA** [comment]
> [@HaidaoLin-NOAA](https://github.com/HaidaoLin-NOAA) My `postxconfig-NT.txt` file can be found here: https://github.com/SamuelDegelia-NOAA/rrfs-workflow/blob/feature/remove_bt_upp/fix/upp/postxconfig-NT.txt
> 
> I also have it on Hera here if you would rather grab it that way: `/scratch4/BMC/zrtrr/Samuel.Degelia/rrfs-workflow_20250723/rrfs-workflow/fix/upp/postxconfig-NT.txt`
> 
> I did not change `mpas_hrrr_postcntrl.xml` or anything else. This single file change seemed to resolve the UPP-related crashes for me.

@SamuelDegelia-NOAA it works.  Thanks!!

**Comment by guoqing-noaa** [comment]
@EricJames-NOAA Thanks for looking further into this. While you are working on a permanent solution, can we remove the BT from the UPP process for now?
