### ISSUE TITLE
Prefix of j-job and ex-scripts should be changed from regional to rrfs

### ISSUE THREAD

**Issue by chan-hoo** [NOAA-EMC/rrfs-workflow#65]
- The j-jobs and ex-scripts need to be renamed from `JREGIONAL_ / exregional_` to `JRRFS_ / exrrfs_` because the name of this app is the "rrfs"-workflow.
- The script `preprocess_smoke.py` should be renamed to `exrrfs_process_smoke.py`.

**Comment by chan-hoo** [comment]
@MatthewPyle-NOAA, @BenjaminBlake-NOAA, do you agree with this change ("exrrfs_xxx")? or isn't this necessary?

**Comment by MatthewPyle-NOAA** [comment]
@chan-hoo I would consider it a good change as well.  I don't think this is adhered to by all legacy systems (GFS), but it would make NCO happy for a new system.
