### ISSUE TITLE
Add BUFRSND output processing to ensemble forecast members

### ISSUE THREAD

**Issue by MatthewPyle-NOAA** [NOAA-EMC/rrfs-workflow#79]
Currently we only run the BUFR postprocessing job for the deterministic member.  We've had requests from several stakeholders to include it for the ensemble members as well, and seems like a good thing to add within this workflow.  I believe it would just require adding a block to the .xml file used to run the ensemble forecasts.

**Comment by MatthewPyle-NOAA** [comment]
I could use some guidance from @hu5970 or @ShunLiu-NOAA.  It looks like ush/sample_configs/RRFS_A/config.sh_rrfs_a_enkf_n3 has the ability to build both the rrfs_na_enfcst and rrfs_na_enkf .xml files.  Do you run ush/generate_FV3LAM_wflow.sh twice based on this type of config file, just changing DO_ENSFCST="TRUE" to make the rrfs_na_enfcst setup?   Thanks!

**Comment by hu5970** [comment]
Yes. The ush/sample_configs/RRFS_A/config.sh_rrfs_a_enkf_n3 is used to generate both ensemble DA cycles and ensemble forecast. The default is to generate the ensemble DA. If you un-comment DO_ENSFCST="TRUE", it generates the system  (rrfs_na_enfcst) for running ensemble forecast.

**Comment by MatthewPyle-NOAA** [comment]
Thanks for the confirmation @hu5970
