### ISSUE TITLE
simplify user input when running app_build.sh on given HPC platforms

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/rrfs-workflow#81]
The rrfs-workflow already has a script (ush/fix_rrfs_locations.sh) which can detect user's current HPC platform (wcoss2, hera, jet, orion, etc) automatically. In this sense, users can just enter `./app_build.sh` without the need to explicitly specifying the "--platform" command-line parameter.

@MatthewPyle-NOAA and @chan-hoo Are you okay that I create a PR to bring the simplification to the rrfs-workflow?

**Comment by chan-hoo** [comment]
@MatthewPyle-NOAA, is this kind of auto-detection acceptable for EE2 compliance? If so, this would be fine with me.

**Comment by MatthewPyle-NOAA** [comment]
@chan-hoo I don't see a problem with it.  And if it did become an issue for some reason, would be easy to change.

**Comment by chan-hoo** [comment]
@guoqing-noaa, when you make this change, please do not remove the `--platform (-p)` argument. Instead, you can set it as an option. I mean that either `./app_build.sh` or `./app_build.sh -p=(machine)` should work.
