### ISSUE TITLE
"One time step" issue in ensemble initialization step

### ISSUE THREAD

**Issue by delippi** [NOAA-EMC/rrfs-workflow#84]
DO_ENSINIT=TRUE enables the 1 time step part of the workflow. The only purpose of this is to "convert" cold starts from chgres_cube into warm starts by running the model for a single time step. This is done because warm start/restarts are needed for the recentering.

The problem:
We run the model for 1 time step (36s) and then use that t+36s restart file as initial conditions starting at t+0s by resetting the time step back to zero by modifying coupler.res replacing the 36s information with 0s.

The solution:
Eliminate the ENSINIT step completely and replace it with the blending tools that converts cold starts to warm starts.

**Comment by MatthewPyle-NOAA** [comment]
Should be invoked with v0.7.7 upgrade.

**Comment by JacobCarley-NOAA** [comment]
I think this one is complete. @delippi can you confirm?

**Comment by delippi** [comment]
@MatthewPyle-NOAA @JacobCarley-NOAA , yes this one is complete.
