### ISSUE TITLE
err_chk does not make rocoto tasks dead 

### ISSUE THREAD

**Issue by chan-hoo** [NOAA-EMC/rrfs-workflow#86]
`err_chk` and `err_exit` do not work correctly on other machines such as Hera, Jet, and Orion.
When running executables fails, the `err_chk` function detects them as `FATAL ERROR`. 
However, the rocoto status for the corresponding task does not turn to `DEAD` and the next tasks are launched. 
This is caused by that `err_exit` and `err_chk` work correctly only on WCOSS2.

**Comment by MatthewPyle-NOAA** [comment]
Work has been done on err_exit: https://github.com/NOAA-EMC/NCEPLIBS-prod_util/pull/69
